#!/bin/bash

touch "ISSUE: Archived (Old or Unwanted) Documents in Search Results"
touch "ISSUE: Cannot Turn Off Search Suggestions "
touch "ISSUE: Content Fields Not Indexed"
touch "ISSUE: Content Source Not Indexed "
touch "ISSUE: Incorrect Search Results for Some Characters"
touch "ISSUE: Lithium Results Are Broken"
touch "ISSUE: No Way to Exclude Documents from Search "
touch "ISSUE: Results Break and Get Fixed Automatically"
touch "ISSUE: Tuning a Keyword Doesn't Change Results for Its Synonyms"
touch "ISSUE: Cannot Index Google Drive"
touch "ISSUE: Cannot Index Lithium and Other Communities "
touch "ISSUE: Cannot Index Salesforce"
touch "ISSUE: Cannot Index YouTube and Vimeo"
touch "ISSUE: Cannot Index Website"
